def getjsonform():
  objects = {
              "version": "4.6.0",
              "flags": {},
              "shapes": [],
              "imagePath": "0001.jpg",
              "imageData": None,
              "imageHeight": 0,
              "imageWidth": 0,
              "Temperature": 0,
              "Salinity": 0,
              "DO": 0,
              "pH": 0,
              "Longitude": 0,
              "Latitude": 0,
              "Depth": 5.4,
              "Location": "",
              "Weather": 0,
              "Transparency": 0,
              "Date_created": "2000-01-01", 
              # "Source_video": None,
              # "Video_time" : None,
              # "Frame_no": None,
            }
  return objects